In [1]:
import pandas as pd
import datetime

In [2]:
class money_tracker_month:
    def __init__(self, month_number=datetime.date.today().month):
        self.day = datetime.date.today().day
        self.month_number = month_number
        self.year = datetime.date.today().year
        self.num_to_month = {
            1: 'Январь', 2: 'Февраль', 3: 'Март', 4: 'Апрель', 5: 'Май', 6: 'Июнь',
            7: 'Июль', 8: 'Август', 9: 'Сентябрь', 10: 'Октябрь', 11: 'Ноябрь', 12: 'Декабрь' }
        self.month_name = self.num_to_month[month_number]
        self.date = datetime.datetime(day=self.day, month=self.month_number, year=self.year)

        self.table = pd.DataFrame({'дата': [], 'категория': [], 'сумма': [], 'комментарий': []})
        self.table_name = str(self.month_name)+'_'+str(self.year)+'.xlsx'

        self.expenses_group =  {1: 'продукты',
                               2: 'транспорт',
                               3: 'развлечения',
                               4: 'здоровье',
                               5: 'связь',
                               6: 'квартплата',
                               7: 'непредвиденное',
                               8: 'одежда',
                               9: 'цифровые',
                               10: 'ненужные',
                               11: 'прочее'}
        
        self.gain_group = {100: 'зарплата',
                           101: 'подработка',
                           102: 'дивиденды',
                           103: 'депозиты'}

    def create_xlsx(self, filename=None):
        if filename == None:
            self.table.to_excel(self.table_name, index=0)
        else:
            self.table_name = filename
            self.table.to_excel(filename, index=0)

    def read_xlsx(self, filename=None):
        if filename == None:
            self.table = pd.read_excel(self.table_name)
        else:
            self.table_name = filename
            self.table = pd.read_excel(filename)

            self.month_name = filename.split('_')[0]
            for key, value in self.num_to_month.items():
                if self.month_name == value:
                    self.month_number = key
            self.year = int(filename.split('_')[1].split('.')[0])

            self.date = datetime.datetime(day=self.day, month=self.month_number, year=self.year)

    def write_xlsx(self):
        self.table.to_excel(self.table_name, index=0)

    def get_expenses_group(self):
        print('Группы расходов:')
        for key, value in self.expenses_group.items():
            print("{:>2}".format(key), end='|')
            print("{:<15}".format(value)+'|')
        print()

        print('Группы доходов:')
        for key, value in self.gain_group.items():
            print("{:>2}".format(key), end='|')
            print("{:<15}".format(value)+'|')
        print()

    def add_expenses_manual(self, date=0, category='прочее', value=0,  comment=''):
        self.table.loc[len(self.table)] = [date, category, value, comment]

    def add_expenses_auto(self):
        flag = True
        month_num = "{:>02d}".format(self.month_number)
        while True:
            date = "{:>02d}".format(int(input('Дата = '))) + '.' + month_num + '.' + str(self.year)

            num_category = int(input('Категория = '))

            cost = int(input('Сумма = '))
            if num_category in self.expenses_group.keys():
                self.table.loc[len(self.table)] = [date, self.expenses_group[num_category], -cost, str(input('Комментарий = '))]
            elif num_category in self.gain_group.keys():
                self.table.loc[len(self.table)] = [date, self.gain_group[num_category], cost, str(input('Комментарий = '))]
            else:
                pass
                # добавить ошибку ввода

            if str(input('Продолжить?[Y/n]')) == 'n':
                break

In [3]:
first = money_tracker_month()
# print(first.day, first.month_name, first.year)
# first.create_xlsx(filename='Сентябрь_2024.xlsx')
first.write_xlsx()

In [4]:
first.read_xlsx(filename='2024/Сентябрь_2024.xlsx')
first.table

          дата   категория  сумма            комментарий
0   04.11.2024       связь   -600                     t2
1   19.11.2024    продукты   -651            Перекресток
2   25.11.2024       связь   -599                 iCloud
3   01.11.2024      прочее      0                    NaN
4   01.11.2024    продукты  -7500           Перевод Даше
5   01.11.2024  квартплата  -1090        Стройка и точка
6   01.11.2024  квартплата -15000    За квартиру Люберцы
7   01.11.2024    продукты   -500                    Да!
8   02.11.2024   транспорт   -300  Автопополнение тройка
9   02.11.2024    продукты   -364              Пятерочка
10  03.11.2024    продукты   -480                  Милти
11  04.11.2024   транспорт  -1894                    РЖД
12  05.11.2024   транспорт   -300                 Тройка
13  05.11.2024    продукты   -310                  Милти
14  05.11.2024   транспорт   -300                 Тройка
15  08.11.2024    продукты   -190       IP BELIAKOV M.A.
16  09.11.2024    ненужные   -600         ДР Юлии и Вани
17  11.11.2024  квартплата  -4698            Инструменты
18  12.11.2024    продукты  -5000                   Даше
19  12.11.2024    продукты  -1396                    Да!
20  15.11.2024      одежда  -2878                  Остин
21  15.11.2024    продукты   -212                     КБ
22  16.11.2024    зарплата  38100                     ЗП
23  16.11.2024    здоровье  -1200                   HOST
24  17.11.2024   транспорт   -300                 Тройка
25  18.11.2024       связь   -650                    VTB
26  18.11.2024    цифровые  -4599                    DNS
27  18.11.2024    продукты   -149                     КБ
28  19.11.2024   транспорт   -300                 Тройка
29  19.11.2024    продукты   -620                  Милти
30  19.11.2024    продукты   -128              Пятерочка
31  19.11.2024   транспорт   -300                     20
32  20.11.2024    продукты   -155                  Точка
33  20.11.2024    продукты   -190                  XPLAT
34  21.11.2024    продукты    -70                  XPLAT
35  23.11.2024    ненужные   -500               ДР Влада
36  23.11.2024    здоровье  -4402      Лекарства Бабушке
37  24.11.2024   транспорт   -600                 Тройка
38  24.11.2024    продукты   -283                  Parle
39  24.11.2024    продукты   -250                  Милти
40  24.11.2024    продукты   -170                   Спар
41  25.11.2024    продукты   -230                  Милти
42  26.11.2024      одежда  -2700           Футболка ДИТ
43  26.11.2024   транспорт   -300                 Тройка
44  26.11.2024    продукты   -155              Пятерочка
45  28.11.2024  квартплата -14000                  Шкафы
46  29.11.2024    продукты   -400                  Дикси
47  29.11.2024    цифровые   -199                    igm
48  30.11.2024    депозиты   2289              Вклад ВТБ

In [5]:
first.get_expenses_group()

Группы расходов:
 1|продукты       |
 2|транспорт      |
 3|развлечения    |
 4|здоровье       |
 5|связь          |
 6|квартплата     |
 7|непредвиденное |
 8|одежда         |
 9|цифровые       |
10|ненужные       |
11|прочее         |

Группы доходов:
100|зарплата       |
101|подработка     |
102|дивиденды      |
103|депозиты       |

In [6]:
first.add_expenses_auto()
first.write_xlsx()
first.table.tail()

          дата категория  сумма                    комментарий
51  14.11.2024  цифровые  -9013              Озон. Колонка JBL
52  17.11.2024    одежда   -395               Озон. Носки Omsa
53  24.11.2024  продукты   -516                   Озон. Nut&Go
54  29.11.2024  продукты   -327                  Озон. Леденцы
55  30.11.2024  цифровые  -2867  Свич Baseus и полка для стола

In [7]:
first.write_xlsx()

In [8]:
first.table.tail()

          дата категория  сумма                    комментарий
51  14.11.2024  цифровые  -9013              Озон. Колонка JBL
52  17.11.2024    одежда   -395               Озон. Носки Omsa
53  24.11.2024  продукты   -516                   Озон. Nut&Go
54  29.11.2024  продукты   -327                  Озон. Леденцы
55  30.11.2024  цифровые  -2867  Свич Baseus и полка для стола

In [20]:
import os

In [21]:
class money_tracker_year:
    def __init__(self):
        self.year = datetime.date.today().year
        self.year = 2024
        print(self.year)
        self.num_to_month = {
            1: 'Январь', 2: 'Февраль', 3: 'Март', 4: 'Апрель', 5: 'Май', 6: 'Июнь',
            7: 'Июль', 8: 'Август', 9: 'Сентябрь', 10: 'Октябрь', 11: 'Ноябрь', 12: 'Декабрь' }

        self.table = pd.DataFrame({'категория': []})
        self.table_name = str(self.year)+'.xlsx'

        self.expenses_group =  {1: 'продукты',
                               2: 'транспорт',
                               3: 'развлечения',
                               4: 'здоровье',
                               5: 'связь',
                               6: 'квартплата',
                               7: 'непредвиденное',
                               8: 'одежда',
                               9: 'цифровые',
                               10: 'ненужные',
                               11: 'прочее'}
        
        self.gain_group = {100: 'зарплата',
                           101: 'подработка',
                           102: 'дивиденды',
                           103: 'депозиты'}

    def create_xlsx(self, filename=None):
        if filename == None:
            self.table.to_excel(self.table_name, index=0)
        else:
            self.table_name = filename
            self.table.to_excel(filename, index=0)

    def read_xlsx(self, filename=None):
        if filename == None:
            self.table = pd.read_excel(self.table_name)
        else:
            self.table_name = filename
            self.table = pd.read_excel(filename)

            self.year = int(filename.split('.')[0])

    def write_xlsx(self):
        self.table.to_excel(self.table_name, index=0)

    def get_expenses_group(self):
        print('Группы расходов:')
        for key, value in self.expenses_group.items():
            print("{:>2}".format(key), end='|')
            print("{:<15}".format(value)+'|')
        print()

        print('Группы доходов:')
        for key, value in self.gain_group.items():
            print("{:>2}".format(key), end='|')
            print("{:<15}".format(value)+'|')
        print()

    def add_expenses_gpoup(self):
        for value in self.expenses_group.values():
            self.table.loc[len(self.table)] = [value]
        self.table.loc[len(self.table)] = ['    ']
        for value in self.gain_group.values():
            self.table.loc[len(self.table)] = [value]

    def add_months_data(self):
        files = os.listdir('2024')
        # files.append(os.listdir('2024'))
        # print(files)
        for file in files:
            if file[0] != '.':
                # try:
                #     self.month = pd.read_excel('2023/'+file)
                # except:
                self.month = pd.read_excel('2024/'+file)

                month_sum_arr = []    
                for value in self.expenses_group.values():
                    month_sum_arr.append(self.month[self.month['категория'] == value]['сумма'].sum())
                month_sum_arr.append('  ')
                for value in self.gain_group.values():
                    month_sum_arr.append(self.month[self.month['категория'] == value]['сумма'].sum())

                self.table[file.split('.')[0]] = month_sum_arr

In [22]:
print(os.listdir('2024'))

['Март_2024.xlsx', '.DS_Store', 'Апрель_2024.xlsx', 'Май_2024.xlsx', 'Июнь_2024.xlsx', 'Июль_2024.xlsx']

In [23]:
y2023 = money_tracker_year()
# y2023.create_xlsx()
# y2023.write_xlsx()
# y2023.add_expenses_gpoup()
y2023.read_xlsx()
y2023.table

2024

,категория,Январь_2024,Февраль_2024,Март_2024,Апрель_2024,Май_2024,Июнь_2024,Июль_2024
0,Продукты,-3755,-6300,-1896,-5038,-6098,-16604,-16970
1,Транспорт,-2096,-2161,-4787,-8387,-8444,-3190,-3785
2,Развлечения,0,-3054,-2462,-6610,0,0,-2490
3,Здоровье,-1552,0,-1200,-1200,-3217,-1200,-1200
4,Связь,-650,-1749,-1249,-629,-1199,-1349,-1499
5,Квартплата,-15000,-15000,-15362,-17120,0,-578,-64247
6,Непредвиденное,0,-500,0,0,0,0,0
7,Одежда,0,-7697,0,0,0,-15267,-2320
8,Цифровые,-390,0,-1951,0,-3999,-1571,-7946
9,Ненужное,0,-1642,-2624,-800,0,0,-750
10,Прочее,-49803,-7428,-53124,0,-20836,-9715,-1499
11,NaN,,,,,,,
12,Зарплата,43381,71102,40000,40000,30000,40000,153335
13,Подработка,5038,1128,100,1600,3152,1780,2000
14,Дивиденды,0,0,0,0,0,300,0
15,Депозиты,0,0,0,0,0,0,1864

In [24]:
y2023.add_months_data()

In [25]:
y2023.table

,категория,Январь_2024,Февраль_2024,Март_2024,Апрель_2024,Май_2024,Июнь_2024,Июль_2024
0,Продукты,-3755,-6300,-1896,-5038,-6098,-16604,-16970
1,Транспорт,-2096,-2161,-4787,-8387,-8444,-3190,-3785
2,Развлечения,0,-3054,-2462,-6610,0,0,-2490
3,Здоровье,-1552,0,-1200,-1200,-3217,-1200,-1200
4,Связь,-650,-1749,-1249,-629,-1199,-1349,-1499
5,Квартплата,-15000,-15000,-15362,-17120,0,-578,-64247
6,Непредвиденное,0,-500,0,0,0,0,0
7,Одежда,0,-7697,0,0,0,-15267,-2320
8,Цифровые,-390,0,-1951,0,-3999,-1571,-7946
9,Ненужное,0,-1642,-2624,-800,0,0,-750
10,Прочее,-49803,-7428,-53124,0,-20836,-9715,-1499
11,NaN,,,,,,,
12,Зарплата,43381,71102,40000,40000,79548,100717,153335
13,Подработка,5038,1128,100,1600,3152,1780,2000
14,Дивиденды,0,0,0,0,0,300,0
15,Депозиты,0,0,0,0,0,0,1864

In [19]:
y2023.write_xlsx()

In [27]:
y2024 = money_tracker_year()
y2024.create_xlsx()
y2024.write_xlsx()
y2024.add_expenses_gpoup()
y2024.read_xlsx()
y2024.table

2024

Empty DataFrame
Columns: [категория]
Index: []

In [18]:
y2024.add_months_data()
y2024.table

NameError: name 'y2024' is not defined

In [29]:
y2024.write_xlsx()